/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCBASEDS_DATA_H_RPCGEN
#define _RPCBASEDS_DATA_H_RPCGEN


typedef long HRESULT;

struct RPCRES_LONG {
	HRESULT result;
	long data;
};
typedef struct RPCRES_LONG RPCRES_LONG;

struct USB_DEVICE_CONFIG_INFO {
	HRESULT ret;
	long usb_ai_samplerate;
	long usb_ai_format;
	long usb_ai_chnum;
};
typedef struct USB_DEVICE_CONFIG_INFO USB_DEVICE_CONFIG_INFO;

struct RPC_CONNECTION {
	long srcInstanceID;
	long srcPinID;
	long desInstanceID;
	long desPinID;
	long mediaType;
};
typedef struct RPC_CONNECTION RPC_CONNECTION;

struct RPC_SEND_LONG {
	long instanceID;
	long pinID;
	long data;
};
typedef struct RPC_SEND_LONG RPC_SEND_LONG;

#endif /* !_RPCBASEDS_DATA_H_RPCGEN */
