/**************************************************************************//**
 * @file     rtl8710c_crypto.h
 * @brief    This file defines crypto type ,device address and declare device module macro variables.
 * @version  1.0
 * @date     9. July 2018
 * @note     Generated by SVDConv V3.3.9 on Thursday, 21.09.2017 17:03:48
 *           from File 'rtl8710c_crypto.svd',
 *           last modified on Thursday, 21.09.2017 09:03:15
 *
 *******************************************************************************
 *
 * Copyright(c) 2007 - 2017 Realtek Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 ******************************************************************************/
/** @addtogroup hs_hal_crypto CRYPTO
 *  @ingroup 8710c_hal
 *  @{
 *  @brief The Crypto HAL. This crypto implements functions for cryptographic,such as
 *         calculating CRC value, authentication, encryption and decryption.
 */
#ifndef RTL8735B_CRYPTO_H
#define RTL8735B_CRYPTO_H

#ifdef __cplusplus
extern "C" {
#endif

#include "basic_types.h"

/* ================================================================================================================= */
/* ================                            Device Specific Peripheral Section                             ====== */
/* ================================================================================================================= */

/// @cond DOXYGEN_CRYPTO_REG_TYPE

/** @addtogroup crypto_device_reg Crypto Engine Registers.
 *  @ingroup hs_hal_crypto
 *  @{
 */


/* ================================================================================================================ */
/* ================                          Device Specific Peripheral Address Map                           ===== */
/* ================================================================================================================ */


/** @addtogroup device_crypto_addr Crypto Engine Register Base Address
 *  @ingroup hs_hal_crypto
 *  @{
 */

#define CRYPTO_S_BASE                 0x50070000UL
#define CRYPTO_NS_BASE                0x40070000UL

/** @} */ /* End of group device_crypto_addr */


/* ================================================================================================================ */
/* ================                                  Peripheral declaration                                   ===== */
/* ================================================================================================================ */


/** @addtogroup device_crypto_decl Crypto Engine Device Type
 *  @ingroup hs_hal_crypto
 *  @{
 */

#define CRYPTO_S_MODULE                         ((CRYPTO_Type *)            CRYPTO_S_BASE)
#define CRYPTO_NS_MODULE                        ((CRYPTO_Type *)            CRYPTO_NS_BASE)

/** @} */ /* End of group device_crypto_decl */

/// @endcond /* End of condition DOXYGEN_CRYPTO_REG_TYPE */
#ifdef __cplusplus
}
#endif

#endif /* RTL8710C_CRYPTO_H */

/** @} */ /* End of group hs_hal_crypto */

