name=AmebaMultithreading
version=1.0.0
author=Realtek SG
maintainer=Realtek SG
sentence=Ameba Multithreading API
paragraph=With this you can do multithreading operations
category=Multithreading
url=
architectures=AmebaPro2