#ifndef ROM_SSL_FUNC_RENAME_H
#define ROM_SSL_FUNC_RENAME_H

// bignum
#define mbedtls_mpi_init                     _mbedtls_mpi_init
#define mbedtls_mpi_free                     _mbedtls_mpi_free
#define mbedtls_mpi_grow                     _mbedtls_mpi_grow
#define mbedtls_mpi_shrink                   _mbedtls_mpi_shrink
#define mbedtls_mpi_copy                     _mbedtls_mpi_copy
#define mbedtls_mpi_swap                     _mbedtls_mpi_swap
#define mbedtls_mpi_safe_cond_assign         _mbedtls_mpi_safe_cond_assign
#define mbedtls_mpi_safe_cond_swap           _mbedtls_mpi_safe_cond_swap
#define mbedtls_mpi_lset                     _mbedtls_mpi_lset
#define mbedtls_mpi_get_bit                  _mbedtls_mpi_get_bit
#define mbedtls_mpi_set_bit                  _mbedtls_mpi_set_bit
#define mbedtls_mpi_lsb                      _mbedtls_mpi_lsb
#define mbedtls_mpi_bitlen                   _mbedtls_mpi_bitlen
#define mbedtls_mpi_size                     _mbedtls_mpi_size
#define mbedtls_mpi_read_binary              _mbedtls_mpi_read_binary
#define mbedtls_mpi_write_binary             _mbedtls_mpi_write_binary
#define mbedtls_mpi_shift_l                  _mbedtls_mpi_shift_l
#define mbedtls_mpi_shift_r                  _mbedtls_mpi_shift_r
#define mbedtls_mpi_cmp_abs                  _mbedtls_mpi_cmp_abs
#define mbedtls_mpi_cmp_mpi                  _mbedtls_mpi_cmp_mpi
#define mbedtls_mpi_cmp_int                  _mbedtls_mpi_cmp_int
#define mbedtls_mpi_add_abs                  _mbedtls_mpi_add_abs
#define mbedtls_mpi_sub_abs                  _mbedtls_mpi_sub_abs
#define mbedtls_mpi_add_mpi                  _mbedtls_mpi_add_mpi
#define mbedtls_mpi_sub_mpi                  _mbedtls_mpi_sub_mpi
#define mbedtls_mpi_add_int                  _mbedtls_mpi_add_int
#define mbedtls_mpi_sub_int                  _mbedtls_mpi_sub_int
#define mbedtls_mpi_mul_mpi                  _mbedtls_mpi_mul_mpi
#define mbedtls_mpi_read_string              _mbedtls_mpi_read_string
#define mbedtls_mpi_mul_int                  _mbedtls_mpi_mul_int
#define mbedtls_mpi_div_mpi                  _mbedtls_mpi_div_mpi
#define mbedtls_mpi_div_int                  _mbedtls_mpi_div_int
#define mbedtls_mpi_mod_mpi                  _mbedtls_mpi_mod_mpi
#define mbedtls_mpi_mod_int                  _mbedtls_mpi_mod_int
#define mbedtls_mpi_write_string             _mbedtls_mpi_write_string
#define mbedtls_mpi_exp_mod                  _mbedtls_mpi_exp_mod
#define mbedtls_mpi_gcd                      _mbedtls_mpi_gcd
#define mbedtls_mpi_fill_random              _mbedtls_mpi_fill_random
#define mbedtls_mpi_inv_mod                  _mbedtls_mpi_inv_mod
#define mbedtls_mpi_is_prime                 _mbedtls_mpi_is_prime
#define mbedtls_mpi_gen_prime                _mbedtls_mpi_gen_prime
// ecp
#define mbedtls_ecp_curve_list               _mbedtls_ecp_curve_list
#define mbedtls_ecp_curve_info_from_grp_id   _mbedtls_ecp_curve_info_from_grp_id
#define mbedtls_ecp_curve_info_from_tls_id   _mbedtls_ecp_curve_info_from_tls_id
#define mbedtls_ecp_curve_info_from_name     _mbedtls_ecp_curve_info_from_name
#define mbedtls_ecp_point_init               _mbedtls_ecp_point_init
#define mbedtls_ecp_group_init               _mbedtls_ecp_group_init
#define mbedtls_ecp_keypair_init             _mbedtls_ecp_keypair_init
#define mbedtls_ecp_point_free               _mbedtls_ecp_point_free
#define mbedtls_ecp_group_free               _mbedtls_ecp_group_free
#define mbedtls_ecp_keypair_free             _mbedtls_ecp_keypair_free
#define mbedtls_ecp_copy                     _mbedtls_ecp_copy
#define mbedtls_ecp_group_copy               _mbedtls_ecp_group_copy
#define mbedtls_ecp_set_zero                 _mbedtls_ecp_set_zero
#define mbedtls_ecp_is_zero                  _mbedtls_ecp_is_zero
#define mbedtls_ecp_point_cmp                _mbedtls_ecp_point_cmp
#define mbedtls_ecp_point_read_string        _mbedtls_ecp_point_read_string
#define mbedtls_ecp_point_write_binary       _mbedtls_ecp_point_write_binary
#define mbedtls_ecp_point_read_binary        _mbedtls_ecp_point_read_binary
#define mbedtls_ecp_tls_read_point           _mbedtls_ecp_tls_read_point
#define mbedtls_ecp_tls_write_point          _mbedtls_ecp_tls_write_point
#define mbedtls_ecp_tls_read_group           _mbedtls_ecp_tls_read_group
#define mbedtls_ecp_tls_write_group          _mbedtls_ecp_tls_write_group
#define mbedtls_ecp_check_pubkey             _mbedtls_ecp_check_pubkey
#define mbedtls_ecp_check_privkey            _mbedtls_ecp_check_privkey
#define mbedtls_ecp_mul                      _mbedtls_ecp_mul
#define mbedtls_ecp_muladd                   _mbedtls_ecp_muladd
#define mbedtls_ecp_gen_keypair_base         _mbedtls_ecp_gen_keypair_base
#define mbedtls_ecp_gen_keypair              _mbedtls_ecp_gen_keypair
#define mbedtls_ecp_gen_key                  _mbedtls_ecp_gen_key
#define mbedtls_ecp_check_pub_priv           _mbedtls_ecp_check_pub_priv
// ecp_curves
#define mbedtls_ecp_group_load               _mbedtls_ecp_group_load
// sha1
#define mbedtls_sha1_init                    _mbedtls_sha1_init
#define mbedtls_sha1_free                    _mbedtls_sha1_free
#define mbedtls_sha1_clone                   _mbedtls_sha1_clone
#define mbedtls_sha1_starts                  _mbedtls_sha1_starts
#define mbedtls_sha1_process                 _mbedtls_sha1_process
#define mbedtls_sha1_update                  _mbedtls_sha1_update
#define mbedtls_sha1_finish                  _mbedtls_sha1_finish
#define mbedtls_sha1                         _mbedtls_sha1
// sha256
#define mbedtls_sha256_init                  _mbedtls_sha256_init
#define mbedtls_sha256_free                  _mbedtls_sha256_free
#define mbedtls_sha256_clone                 _mbedtls_sha256_clone
#define mbedtls_sha256_starts                _mbedtls_sha256_starts
#define mbedtls_sha256_process               _mbedtls_sha256_process
#define mbedtls_sha256_update                _mbedtls_sha256_update
#define mbedtls_sha256_finish                _mbedtls_sha256_finish
#define mbedtls_sha256                       _mbedtls_sha256
// sha512
#define mbedtls_sha512_init                  _mbedtls_sha512_init
#define mbedtls_sha512_free                  _mbedtls_sha512_free
#define mbedtls_sha512_clone                 _mbedtls_sha512_clone
#define mbedtls_sha512_starts                _mbedtls_sha512_starts
#define mbedtls_sha512_process               _mbedtls_sha512_process
#define mbedtls_sha512_update                _mbedtls_sha512_update
#define mbedtls_sha512_finish                _mbedtls_sha512_finish
#define mbedtls_sha512                       _mbedtls_sha512
// oid
#define mbedtls_oid_get_attr_short_name      _mbedtls_oid_get_attr_short_name
#define mbedtls_oid_get_x509_ext_type        _mbedtls_oid_get_x509_ext_type
#define mbedtls_oid_get_extended_key_usage   _mbedtls_oid_get_extended_key_usage
#define mbedtls_oid_get_sig_alg_desc         _mbedtls_oid_get_sig_alg_desc
#define mbedtls_oid_get_sig_alg              _mbedtls_oid_get_sig_alg
#define mbedtls_oid_get_oid_by_sig_alg       _mbedtls_oid_get_oid_by_sig_alg
#define mbedtls_oid_get_pk_alg               _mbedtls_oid_get_pk_alg
#define mbedtls_oid_get_oid_by_pk_alg        _mbedtls_oid_get_oid_by_pk_alg
#define mbedtls_oid_get_ec_grp               _mbedtls_oid_get_ec_grp
#define mbedtls_oid_get_oid_by_ec_grp        _mbedtls_oid_get_oid_by_ec_grp
#define mbedtls_oid_get_cipher_alg           _mbedtls_oid_get_cipher_alg
#define mbedtls_oid_get_md_alg               _mbedtls_oid_get_md_alg
#define mbedtls_oid_get_oid_by_md            _mbedtls_oid_get_oid_by_md
#define mbedtls_oid_get_pkcs12_pbe_alg       _mbedtls_oid_get_pkcs12_pbe_alg
// md5
#define mbedtls_md5_init                     _mbedtls_md5_init
#define mbedtls_md5_free                     _mbedtls_md5_free
#define mbedtls_md5_clone                    _mbedtls_md5_clone
#define mbedtls_md5_starts                   _mbedtls_md5_starts
#define mbedtls_md5_process                  _mbedtls_md5_process
#define mbedtls_md5_update                   _mbedtls_md5_update
#define mbedtls_md5_finish                   _mbedtls_md5_finish
#define mbedtls_md5                          _mbedtls_md5
// aes
#define mbedtls_aes_init                     _mbedtls_aes_init
#define mbedtls_aes_free                     _mbedtls_aes_free
#define mbedtls_aes_setkey_enc               _mbedtls_aes_setkey_enc
#define mbedtls_aes_setkey_dec               _mbedtls_aes_setkey_dec
#define mbedtls_aes_encrypt                  _mbedtls_aes_encrypt
#define mbedtls_aes_decrypt                  _mbedtls_aes_decrypt
#define mbedtls_aes_crypt_ecb                _mbedtls_aes_crypt_ecb
#define mbedtls_aes_crypt_cbc                _mbedtls_aes_crypt_cbc
#define mbedtls_aes_crypt_cfb128             _mbedtls_aes_crypt_cfb128
#define mbedtls_aes_crypt_cfb8               _mbedtls_aes_crypt_cfb8
#define mbedtls_aes_crypt_ctr                _mbedtls_aes_crypt_ctr
// des
#define mbedtls_des_init                     _mbedtls_des_init
#define mbedtls_des_free                     _mbedtls_des_free
#define mbedtls_des3_init                    _mbedtls_des3_init
#define mbedtls_des3_free                    _mbedtls_des3_free
#define mbedtls_des_key_set_parity           _mbedtls_des_key_set_parity
#define mbedtls_des_key_check_key_parity     _mbedtls_des_key_check_key_parity
#define mbedtls_des_key_check_weak           _mbedtls_des_key_check_weak
#define mbedtls_des_setkey                   _mbedtls_des_setkey
#define mbedtls_des_setkey_enc               _mbedtls_des_setkey_enc
#define mbedtls_des_setkey_dec               _mbedtls_des_setkey_dec
#define mbedtls_des3_set2key_enc             _mbedtls_des3_set2key_enc
#define mbedtls_des3_set2key_dec             _mbedtls_des3_set2key_dec
#define mbedtls_des3_set3key_enc             _mbedtls_des3_set3key_enc
#define mbedtls_des3_set3key_dec             _mbedtls_des3_set3key_dec
#define mbedtls_des_crypt_ecb                _mbedtls_des_crypt_ecb
#define mbedtls_des_crypt_cbc                _mbedtls_des_crypt_cbc
#define mbedtls_des3_crypt_ecb               _mbedtls_des3_crypt_ecb
#define mbedtls_des3_crypt_cbc               _mbedtls_des3_crypt_cbc
// md
#define mbedtls_md_list                      _mbedtls_md_list
#define mbedtls_md_info_from_string          _mbedtls_md_info_from_string
#define mbedtls_md_info_from_type            _mbedtls_md_info_from_type
#define mbedtls_md_init                      _mbedtls_md_init
#define mbedtls_md_free                      _mbedtls_md_free
#define mbedtls_md_clone                     _mbedtls_md_clone
#define mbedtls_md_setup                     _mbedtls_md_setup
#define mbedtls_md_init_ctx                  _mbedtls_md_init_ctx
#define mbedtls_md_starts                    _mbedtls_md_starts
#define mbedtls_md_update                    _mbedtls_md_update
#define mbedtls_md_finish                    _mbedtls_md_finish
#define mbedtls_md                           _mbedtls_md
#define mbedtls_md_hmac_starts               _mbedtls_md_hmac_starts
#define mbedtls_md_hmac_update               _mbedtls_md_hmac_update
#define mbedtls_md_hmac_finish               _mbedtls_md_hmac_finish
#define mbedtls_md_hmac_reset                _mbedtls_md_hmac_reset
#define mbedtls_md_hmac                      _mbedtls_md_hmac
#define mbedtls_md_process                   _mbedtls_md_process
#define mbedtls_md_get_size                  _mbedtls_md_get_size
#define mbedtls_md_get_type                  _mbedtls_md_get_type
#define mbedtls_md_get_name                  _mbedtls_md_get_name
// asn1parse
#define mbedtls_asn1_get_len                 _mbedtls_asn1_get_len
#define mbedtls_asn1_get_tag                 _mbedtls_asn1_get_tag
#define mbedtls_asn1_get_bool                _mbedtls_asn1_get_bool
#define mbedtls_asn1_get_int                 _mbedtls_asn1_get_int
#define mbedtls_asn1_get_mpi                 _mbedtls_asn1_get_mpi
#define mbedtls_asn1_get_bitstring           _mbedtls_asn1_get_bitstring
#define mbedtls_asn1_get_bitstring_null      _mbedtls_asn1_get_bitstring_null
#define mbedtls_asn1_get_sequence_of         _mbedtls_asn1_get_sequence_of
#define mbedtls_asn1_get_alg                 _mbedtls_asn1_get_alg
#define mbedtls_asn1_get_alg_null            _mbedtls_asn1_get_alg_null
#define mbedtls_asn1_free_named_data         _mbedtls_asn1_free_named_data
#define mbedtls_asn1_free_named_data_list    _mbedtls_asn1_free_named_data_list
#define mbedtls_asn1_find_named_data         _mbedtls_asn1_find_named_data
// asn1write
#define mbedtls_asn1_write_len                     _mbedtls_asn1_write_len
#define mbedtls_asn1_write_tag                     _mbedtls_asn1_write_tag
#define mbedtls_asn1_write_raw_buffer              _mbedtls_asn1_write_raw_buffer
#define mbedtls_asn1_write_mpi                     _mbedtls_asn1_write_mpi
#define mbedtls_asn1_write_null                    _mbedtls_asn1_write_null
#define mbedtls_asn1_write_oid                     _mbedtls_asn1_write_oid
#define mbedtls_asn1_write_algorithm_identifier    _mbedtls_asn1_write_algorithm_identifier
#define mbedtls_asn1_write_bool                    _mbedtls_asn1_write_bool
#define mbedtls_asn1_write_int                     _mbedtls_asn1_write_int
#define mbedtls_asn1_write_printable_string        _mbedtls_asn1_write_printable_string
#define mbedtls_asn1_write_ia5_string              _mbedtls_asn1_write_ia5_string
#define mbedtls_asn1_write_bitstring               _mbedtls_asn1_write_bitstring
#define mbedtls_asn1_write_octet_string            _mbedtls_asn1_write_octet_string
#define mbedtls_asn1_store_named_data              _mbedtls_asn1_store_named_data
// base64
#define mbedtls_base64_encode                      _mbedtls_base64_encode
#define mbedtls_base64_decode                      _mbedtls_base64_decode
// rsa
#define mbedtls_rsa_init                           _mbedtls_rsa_init
#define mbedtls_rsa_set_padding                    _mbedtls_rsa_set_padding
#define mbedtls_rsa_check_pubkey                   _mbedtls_rsa_check_pubkey
#define mbedtls_rsa_check_privkey                  _mbedtls_rsa_check_privkey
#define mbedtls_rsa_check_pub_priv                 _mbedtls_rsa_check_pub_priv
#define mbedtls_rsa_public                         _mbedtls_rsa_public
#define mbedtls_rsa_private                        _mbedtls_rsa_private
#define mbedtls_rsa_rsaes_oaep_encrypt             _mbedtls_rsa_rsaes_oaep_encrypt
#define mbedtls_rsa_rsaes_pkcs1_v15_encrypt        _mbedtls_rsa_rsaes_pkcs1_v15_encrypt
#define mbedtls_rsa_pkcs1_encrypt                  _mbedtls_rsa_pkcs1_encrypt
#define mbedtls_rsa_rsaes_oaep_decrypt             _mbedtls_rsa_rsaes_oaep_decrypt
#define mbedtls_rsa_rsaes_pkcs1_v15_decrypt        _mbedtls_rsa_rsaes_pkcs1_v15_decrypt
#define mbedtls_rsa_pkcs1_decrypt                  _mbedtls_rsa_pkcs1_decrypt
#define mbedtls_rsa_rsassa_pss_sign                _mbedtls_rsa_rsassa_pss_sign
#define mbedtls_rsa_rsassa_pkcs1_v15_sign          _mbedtls_rsa_rsassa_pkcs1_v15_sign
#define mbedtls_rsa_pkcs1_sign                     _mbedtls_rsa_pkcs1_sign
#define mbedtls_rsa_rsassa_pss_verify_ext          _mbedtls_rsa_rsassa_pss_verify_ext
#define mbedtls_rsa_rsassa_pss_verify              _mbedtls_rsa_rsassa_pss_verify
#define mbedtls_rsa_rsassa_pkcs1_v15_verify        _mbedtls_rsa_rsassa_pkcs1_v15_verify
#define mbedtls_rsa_pkcs1_verify                   _mbedtls_rsa_pkcs1_verify
#define mbedtls_rsa_free                           _mbedtls_rsa_free
#define mbedtls_rsa_gen_key                        _mbedtls_rsa_gen_key
#define mbedtls_rsa_copy                           _mbedtls_rsa_copy
// ctr_drbg
#define mbedtls_ctr_drbg_init                      _mbedtls_ctr_drbg_init
#define mbedtls_ctr_drbg_free                      _mbedtls_ctr_drbg_free
#define mbedtls_ctr_drbg_set_prediction_resistance _mbedtls_ctr_drbg_set_prediction_resistance
#define mbedtls_ctr_drbg_set_entropy_len           _mbedtls_ctr_drbg_set_entropy_len
#define mbedtls_ctr_drbg_set_reseed_interval       _mbedtls_ctr_drbg_set_reseed_interval
#define mbedtls_ctr_drbg_update                    _mbedtls_ctr_drbg_update
#define mbedtls_ctr_drbg_reseed                    _mbedtls_ctr_drbg_reseed
#define mbedtls_ctr_drbg_seed_entropy_len          _mbedtls_ctr_drbg_seed_entropy_len
#define mbedtls_ctr_drbg_seed                      _mbedtls_ctr_drbg_seed
#define mbedtls_ctr_drbg_random_with_add           _mbedtls_ctr_drbg_random_with_add
#define mbedtls_ctr_drbg_random                    _mbedtls_ctr_drbg_random
// hmac_drbg
#define mbedtls_hmac_drbg_init                      _mbedtls_hmac_drbg_init
#define mbedtls_hmac_drbg_update                    _mbedtls_hmac_drbg_update
#define mbedtls_hmac_drbg_seed_buf                  _mbedtls_hmac_drbg_seed_buf
#define mbedtls_hmac_drbg_reseed                    _mbedtls_hmac_drbg_reseed
#define mbedtls_hmac_drbg_seed                      _mbedtls_hmac_drbg_seed
#define mbedtls_hmac_drbg_set_prediction_resistance _mbedtls_hmac_drbg_set_prediction_resistance
#define mbedtls_hmac_drbg_set_entropy_len           _mbedtls_hmac_drbg_set_entropy_len
#define mbedtls_hmac_drbg_set_reseed_interval       _mbedtls_hmac_drbg_set_reseed_interval
#define mbedtls_hmac_drbg_random_with_add           _mbedtls_hmac_drbg_random_with_add
#define mbedtls_hmac_drbg_random                    _mbedtls_hmac_drbg_random
#define mbedtls_hmac_drbg_free                      _mbedtls_hmac_drbg_free
// pem
#define mbedtls_pem_init                            _mbedtls_pem_init
#define mbedtls_pem_read_buffer                     _mbedtls_pem_read_buffer
#define mbedtls_pem_free                            _mbedtls_pem_free
#define mbedtls_pem_write_buffer                    _mbedtls_pem_write_buffer
// dhm
#define mbedtls_dhm_init                            _mbedtls_dhm_init
#define mbedtls_dhm_read_params                     _mbedtls_dhm_read_params
#define mbedtls_dhm_make_params                     _mbedtls_dhm_make_params
#define mbedtls_dhm_read_public                     _mbedtls_dhm_read_public
#define mbedtls_dhm_make_public                     _mbedtls_dhm_make_public
#define mbedtls_dhm_calc_secret                     _mbedtls_dhm_calc_secret
#define mbedtls_dhm_free                            _mbedtls_dhm_free
#define mbedtls_dhm_parse_dhm                       _mbedtls_dhm_parse_dhm
// ecjpake
#define mbedtls_ecjpake_init                        _mbedtls_ecjpake_init
#define mbedtls_ecjpake_free                        _mbedtls_ecjpake_free
#define mbedtls_ecjpake_setup                       _mbedtls_ecjpake_setup
#define mbedtls_ecjpake_check                       _mbedtls_ecjpake_check
#define mbedtls_ecjpake_read_round_one              _mbedtls_ecjpake_read_round_one
#define mbedtls_ecjpake_write_round_one             _mbedtls_ecjpake_write_round_one
#define mbedtls_ecjpake_read_round_two              _mbedtls_ecjpake_read_round_two
#define mbedtls_ecjpake_write_round_two             _mbedtls_ecjpake_write_round_two
#define mbedtls_ecjpake_derive_secret               _mbedtls_ecjpake_derive_secret
// arc4
#define mbedtls_arc4_init                           _mbedtls_arc4_init
#define mbedtls_arc4_free                           _mbedtls_arc4_free
#define mbedtls_arc4_setup                          _mbedtls_arc4_setup
#define mbedtls_arc4_crypt                          _mbedtls_arc4_crypt
// ecdh
#define mbedtls_ecdh_gen_public                     _mbedtls_ecdh_gen_public
#define mbedtls_ecdh_compute_shared                 _mbedtls_ecdh_compute_shared
#define mbedtls_ecdh_init                           _mbedtls_ecdh_init
#define mbedtls_ecdh_free                           _mbedtls_ecdh_free
#define mbedtls_ecdh_make_params                    _mbedtls_ecdh_make_params
#define mbedtls_ecdh_read_params                    _mbedtls_ecdh_read_params
#define mbedtls_ecdh_get_params                     _mbedtls_ecdh_get_params
#define mbedtls_ecdh_make_public                    _mbedtls_ecdh_make_public
#define mbedtls_ecdh_read_public                    _mbedtls_ecdh_read_public
#define mbedtls_ecdh_calc_secret                    _mbedtls_ecdh_calc_secret
// ecdsa
#define mbedtls_ecdsa_sign                          _mbedtls_ecdsa_sign
#define mbedtls_ecdsa_sign_det                      _mbedtls_ecdsa_sign_det
#define mbedtls_ecdsa_verify                        _mbedtls_ecdsa_verify
#define mbedtls_ecdsa_write_signature               _mbedtls_ecdsa_write_signature
#define mbedtls_ecdsa_write_signature_det           _mbedtls_ecdsa_write_signature_det
#define mbedtls_ecdsa_read_signature                _mbedtls_ecdsa_read_signature
#define mbedtls_ecdsa_genkey                        _mbedtls_ecdsa_genkey
#define mbedtls_ecdsa_from_keypair                  _mbedtls_ecdsa_from_keypair
#define mbedtls_ecdsa_init                          _mbedtls_ecdsa_init
#define mbedtls_ecdsa_free                          _mbedtls_ecdsa_free
// pk
#define mbedtls_pk_init                             _mbedtls_pk_init
#define mbedtls_pk_free                             _mbedtls_pk_free
#define mbedtls_pk_info_from_type                   _mbedtls_pk_info_from_type
#define mbedtls_pk_setup                            _mbedtls_pk_setup
#define mbedtls_pk_setup_rsa_alt                    _mbedtls_pk_setup_rsa_alt
#define mbedtls_pk_can_do                           _mbedtls_pk_can_do
#define mbedtls_pk_verify                           _mbedtls_pk_verify
#define mbedtls_pk_verify_ext                       _mbedtls_pk_verify_ext
#define mbedtls_pk_sign                             _mbedtls_pk_sign
#define mbedtls_pk_decrypt                          _mbedtls_pk_decrypt
#define mbedtls_pk_encrypt                          _mbedtls_pk_encrypt
#define mbedtls_pk_check_pair                       _mbedtls_pk_check_pair
#define mbedtls_pk_get_bitlen                       _mbedtls_pk_get_bitlen
#define mbedtls_pk_debug                            _mbedtls_pk_debug
#define mbedtls_pk_get_name                         _mbedtls_pk_get_name
#define mbedtls_pk_get_type                         _mbedtls_pk_get_type
// pkwrite
#define mbedtls_pk_write_pubkey                     _mbedtls_pk_write_pubkey
#define mbedtls_pk_write_pubkey_der                 _mbedtls_pk_write_pubkey_der
#define mbedtls_pk_write_key_der                    _mbedtls_pk_write_key_der
#define mbedtls_pk_write_pubkey_pem                 _mbedtls_pk_write_pubkey_pem
#define mbedtls_pk_write_key_pem                    _mbedtls_pk_write_key_pem

#endif // ROM_SSL_FUNC_RENAME_H