#ifndef _AMB_USER_SENSOR_LIST_H_
#define _AMB_USER_SENSOR_LIST_H_

#include <sensor.h>

#undef USE_SENSOR

#if defined(ARDUINO_SENSOR_F37)
#define USE_SENSOR SENSOR_F37
#elif defined(ARDUINO_SENSOR_F53)
#define USE_SENSOR SENSOR_F53
#elif defined(ARDUINO_SENSOR_GC2053)
#define USE_SENSOR SENSOR_GC2053
#elif defined(ARDUINO_SENSOR_GC4653)
#define USE_SENSOR SENSOR_GC4653
#elif defined(ARDUINO_SENSOR_GC5035)
#define USE_SENSOR SENSOR_GC5035
#elif defined(ARDUINO_SENSOR_IMX307)
#define USE_SENSOR SENSOR_IMX307
#elif defined(ARDUINO_SENSOR_IMX327)
#define USE_SENSOR SENSOR_IMX327
#elif defined(ARDUINO_SENSOR_IMX662)
#define USE_SENSOR SENSOR_IMX662
#elif defined(ARDUINO_SENSOR_IMX681)
#define USE_SENSOR SENSOR_IMX681
#elif defined(ARDUINO_SENSOR_IMX681_12M)
#define USE_SENSOR SENSOR_IMX681_12M
#elif defined(ARDUINO_IMX681_12M_SEQ)
#define USE_SENSOR IMX681_12M_SEQ
#elif defined(ARDUINO_SENSOR_PS5268)
#define USE_SENSOR SENSOR_PS5268
#elif defined(ARDUINO_SENSOR_OV9734)
#define USE_SENSOR SENSOR_OV9734
#elif defined(ARDUINO_SENSOR_OV50A40)
#define USE_SENSOR SENSOR_OV50A40
#elif defined(ARDUINO_SENSOR_SC2336)
#define USE_SENSOR SENSOR_SC2336
#endif

#endif
