/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUDIORPCBASEDS_H_RPCGEN
#define _AUDIORPCBASEDS_H_RPCGEN

#include <rpc/rpc_struct.h>

#include "audio/AudioRPCBaseDS_data.h"

#ifdef __cplusplus
extern "C" {
#endif


/* the xdr functions */
extern  bool_t xdr_AUDIO_VOID(XDR *, AUDIO_VOID *);
extern  bool_t xdr_AUDIO_RPC_AFE_INIT_CONFIG(XDR *, AUDIO_RPC_AFE_INIT_CONFIG *);
extern  bool_t xdr_AUDIO_RPC_AFE_PROCESS_BUFS(XDR *, AUDIO_RPC_AFE_PROCESS_BUFS *);
extern  bool_t xdr_AUDIO_RPC_ERROR(XDR *, AUDIO_RPC_ERROR *);

#ifdef __cplusplus
}
#endif

#endif /* !_AUDIORPCBASEDS_H_RPCGEN */
