/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUDIORPC_AGENT_H_RPCGEN
#define _AUDIORPC_AGENT_H_RPCGEN

#include <rpc/rpc_struct.h>

#include "audio/AudioRPC_Agent_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <base/RPCBaseDS.h>
#include <audio/AudioRPCBaseDS.h>

#define AUDIO_AGENT 2002
#define VERSION 0

struct REG_STRUCT *AUDIO_AGENT_0_register(struct REG_STRUCT *rnode);
#define AUDIO_RPC_ToSystem_ErrorStatus 1
extern  HRESULT *AUDIO_RPC_ToSystem_ErrorStatus_0(AUDIO_RPC_ERROR *, CLNT_STRUCT *);
extern  HRESULT *AUDIO_RPC_ToSystem_ErrorStatus_0_svc(AUDIO_RPC_ERROR *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_AUDIO_RPC_ToSystem_ErrorStatus_0_svc)(AUDIO_RPC_ERROR *, RPC_STRUCT *, HRESULT *);

#ifdef __cplusplus
}
#endif

#endif /* !_AUDIORPC_AGENT_H_RPCGEN */
