/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUDIORPC_AGENT_DATA_H_RPCGEN
#define _AUDIORPC_AGENT_DATA_H_RPCGEN

#include <base/RPCBaseDS.h>
#include <audio/AudioRPCBaseDS.h>

#endif /* !_AUDIORPC_AGENT_DATA_H_RPCGEN */
