/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUDIORPC_SYSTEM_H_RPCGEN
#define _AUDIORPC_SYSTEM_H_RPCGEN

#include <rpc/rpc_struct.h>

#include "audio/AudioRPC_System_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <base/RPCBaseDS.h>
#include <audio/AudioRPCBaseDS.h>

#define AUDIO_SYSTEM 2001
#define VERSION 0

struct REG_STRUCT *AUDIO_SYSTEM_0_register(struct REG_STRUCT *rnode);
#define AUDIO_RPC_ToAgent_AFE_Init 1
extern  HRESULT *AUDIO_RPC_ToAgent_AFE_Init_0(AUDIO_RPC_AFE_INIT_CONFIG *, CLNT_STRUCT *);
extern  HRESULT *AUDIO_RPC_ToAgent_AFE_Init_0_svc(AUDIO_RPC_AFE_INIT_CONFIG *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_AUDIO_RPC_ToAgent_AFE_Init_0_svc)(AUDIO_RPC_AFE_INIT_CONFIG *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AFE_Process 2
extern  HRESULT *AUDIO_RPC_ToAgent_AFE_Process_0(AUDIO_RPC_AFE_PROCESS_BUFS *, CLNT_STRUCT *);
extern  HRESULT *AUDIO_RPC_ToAgent_AFE_Process_0_svc(AUDIO_RPC_AFE_PROCESS_BUFS *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_AUDIO_RPC_ToAgent_AFE_Process_0_svc)(AUDIO_RPC_AFE_PROCESS_BUFS *, RPC_STRUCT *, HRESULT *);
#define AUDIO_RPC_ToAgent_AFE_Destroy 3
extern  AUDIO_VOID *AUDIO_RPC_ToAgent_AFE_Destroy_0(AUDIO_VOID *, CLNT_STRUCT *);
extern  AUDIO_VOID *AUDIO_RPC_ToAgent_AFE_Destroy_0_svc(AUDIO_VOID *, RPC_STRUCT *, AUDIO_VOID *);
extern  AUDIO_VOID *(*p_AUDIO_RPC_ToAgent_AFE_Destroy_0_svc)(AUDIO_VOID *, RPC_STRUCT *, AUDIO_VOID *);

#ifdef __cplusplus
}
#endif

#endif /* !_AUDIORPC_SYSTEM_H_RPCGEN */
