/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AUDIORPCBASEDS_DATA_H_RPCGEN
#define _AUDIORPCBASEDS_DATA_H_RPCGEN


typedef long AUDIO_VOID;

struct AUDIO_RPC_AFE_INIT_CONFIG {
	int rate;
	int frame_length;
};
typedef struct AUDIO_RPC_AFE_INIT_CONFIG AUDIO_RPC_AFE_INIT_CONFIG;

struct AUDIO_RPC_AFE_PROCESS_BUFS {
	long mic_1;
	long mic_2;
	long ref;
	long mic_out;
};
typedef struct AUDIO_RPC_AFE_PROCESS_BUFS AUDIO_RPC_AFE_PROCESS_BUFS;

struct AUDIO_RPC_ERROR {
	long instance_id;
	long audio_error;
};
typedef struct AUDIO_RPC_ERROR AUDIO_RPC_ERROR;

#endif /* !_AUDIORPCBASEDS_DATA_H_RPCGEN */
