/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SPEECHRPCBASEDS_H_RPCGEN
#define _SPEECHRPCBASEDS_H_RPCGEN

#include <rpc/rpc_struct.h>

#include "speech/SpeechRPCBaseDS_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <base/RPCBaseDS.h>

/* the xdr functions */
extern  bool_t xdr_SPEECH_RPC_STATE(XDR *, SPEECH_RPC_STATE *);
extern  bool_t xdr_SPEECH_RPC_VAD_STATUS(XDR *, SPEECH_RPC_VAD_STATUS *);
extern  bool_t xdr_SPEECH_RPC_KWS_STATUS(XDR *, SPEECH_RPC_KWS_STATUS *);
extern  bool_t xdr_SPEECH_RPC_KEYWORD(XDR *, SPEECH_RPC_KEYWORD *);
extern  bool_t xdr_SPEECH_RPC_CMD(XDR *, SPEECH_RPC_CMD *);
extern  bool_t xdr_SPEECH_RPC_INSTANCE(XDR *, SPEECH_RPC_INSTANCE *);
extern  bool_t xdr_SPEECH_RPC_DATA(XDR *, SPEECH_RPC_DATA *);
extern  bool_t xdr_SPEECH_RPC_SEND_LONG(XDR *, SPEECH_RPC_SEND_LONG *);
extern  bool_t xdr_TEST_RPC_CONNECTION(XDR *, TEST_RPC_CONNECTION *);
extern  bool_t xdr_SPEECH_DEMO_DATA(XDR *, SPEECH_DEMO_DATA *);
extern  bool_t xdr_SPEECH_HANDLER(XDR *, SPEECH_HANDLER *);
extern  bool_t xdr_SPEECH_KWS_IN_DATA(XDR *, SPEECH_KWS_IN_DATA *);
extern  bool_t xdr_SPEECH_VAD_DATA(XDR *, SPEECH_VAD_DATA *);
extern  bool_t xdr_RPCRES_FEED(XDR *, RPCRES_FEED *);
extern  bool_t xdr_SPEECH_ASR_IN_DATA(XDR *, SPEECH_ASR_IN_DATA *);
extern  bool_t xdr_SPEECH_ASR_CMD(XDR *, SPEECH_ASR_CMD *);
extern  bool_t xdr_SPEECH_INIT_SEND(XDR *, SPEECH_INIT_SEND *);

#ifdef __cplusplus
}
#endif

#endif /* !_SPEECHRPCBASEDS_H_RPCGEN */
