/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SPEECHRPC_AGENT_H_RPCGEN
#define _SPEECHRPC_AGENT_H_RPCGEN

#include <rpc/rpc_struct.h>

#include "speech/SpeechRPC_Agent_data.h"

#ifdef __cplusplus
extern "C" {
#endif

#include <base/RPCBaseDS.h>
#include <speech/SpeechRPCBaseDS.h>

#define SPEECH_AGENT 3002
#define VERSION 0

struct REG_STRUCT *SPEECH_AGENT_0_register(struct REG_STRUCT *rnode);
#define SPEECH_RPC_ToSystem_SpeechState 1
extern  HRESULT *SPEECH_RPC_ToSystem_SpeechState_0(SPEECH_RPC_STATE *, CLNT_STRUCT *);
extern  HRESULT *SPEECH_RPC_ToSystem_SpeechState_0_svc(SPEECH_RPC_STATE *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_SPEECH_RPC_ToSystem_SpeechState_0_svc)(SPEECH_RPC_STATE *, RPC_STRUCT *, HRESULT *);
#define SPEECH_RPC_ToSystem_KWSStatus 2
extern  HRESULT *SPEECH_RPC_ToSystem_KWSStatus_0(SPEECH_RPC_KWS_STATUS *, CLNT_STRUCT *);
extern  HRESULT *SPEECH_RPC_ToSystem_KWSStatus_0_svc(SPEECH_RPC_KWS_STATUS *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_SPEECH_RPC_ToSystem_KWSStatus_0_svc)(SPEECH_RPC_KWS_STATUS *, RPC_STRUCT *, HRESULT *);
#define SPEECH_RPC_ToSystem_VADStatus 3
extern  HRESULT *SPEECH_RPC_ToSystem_VADStatus_0(SPEECH_RPC_VAD_STATUS *, CLNT_STRUCT *);
extern  HRESULT *SPEECH_RPC_ToSystem_VADStatus_0_svc(SPEECH_RPC_VAD_STATUS *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_SPEECH_RPC_ToSystem_VADStatus_0_svc)(SPEECH_RPC_VAD_STATUS *, RPC_STRUCT *, HRESULT *);
#define SPEECH_RPC_ToSystem_ASRResult 4
extern  HRESULT *SPEECH_RPC_ToSystem_ASRResult_0(SPEECH_RPC_CMD *, CLNT_STRUCT *);
extern  HRESULT *SPEECH_RPC_ToSystem_ASRResult_0_svc(SPEECH_RPC_CMD *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_SPEECH_RPC_ToSystem_ASRResult_0_svc)(SPEECH_RPC_CMD *, RPC_STRUCT *, HRESULT *);
#define SPEECH_RPC_ToSystem_ASR_Callback 5
extern  HRESULT *SPEECH_RPC_ToSystem_ASR_Callback_0(SPEECH_ASR_CMD *, CLNT_STRUCT *);
extern  HRESULT *SPEECH_RPC_ToSystem_ASR_Callback_0_svc(SPEECH_ASR_CMD *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_SPEECH_RPC_ToSystem_ASR_Callback_0_svc)(SPEECH_ASR_CMD *, RPC_STRUCT *, HRESULT *);
#define SPEECH_RPC_ToSystem_TestData 6
extern  HRESULT *SPEECH_RPC_ToSystem_TestData_0(SPEECH_DEMO_DATA *, CLNT_STRUCT *);
extern  HRESULT *SPEECH_RPC_ToSystem_TestData_0_svc(SPEECH_DEMO_DATA *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_SPEECH_RPC_ToSystem_TestData_0_svc)(SPEECH_DEMO_DATA *, RPC_STRUCT *, HRESULT *);
#define SPEECH_RPC_ToSystem_KWS_Callback 7
extern  HRESULT *SPEECH_RPC_ToSystem_KWS_Callback_0(RPCRES_FEED *, CLNT_STRUCT *);
extern  HRESULT *SPEECH_RPC_ToSystem_KWS_Callback_0_svc(RPCRES_FEED *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_SPEECH_RPC_ToSystem_KWS_Callback_0_svc)(RPCRES_FEED *, RPC_STRUCT *, HRESULT *);
#define SPEECH_RPC_ToSystem_VAD_Callback 8
extern  HRESULT *SPEECH_RPC_ToSystem_VAD_Callback_0(RPCRES_FEED *, CLNT_STRUCT *);
extern  HRESULT *SPEECH_RPC_ToSystem_VAD_Callback_0_svc(RPCRES_FEED *, RPC_STRUCT *, HRESULT *);
extern  HRESULT *(*p_SPEECH_RPC_ToSystem_VAD_Callback_0_svc)(RPCRES_FEED *, RPC_STRUCT *, HRESULT *);

#ifdef __cplusplus
}
#endif

#endif /* !_SPEECHRPC_AGENT_H_RPCGEN */
