/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SPEECHRPC_SYSTEM_DATA_H_RPCGEN
#define _SPEECHRPC_SYSTEM_DATA_H_RPCGEN

#include <base/RPCBaseDS.h>
#include <speech/SpeechRPCBaseDS.h>

#endif /* !_SPEECHRPC_SYSTEM_DATA_H_RPCGEN */
