name: RTD_json_sync

on:
  workflow_dispatch:
  push:
    paths:
      - 'Arduino_package/release/**'

jobs:
  trigger-event:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Trigger Event
        run: |
          # Your script or command to trigger the event
          echo "Push to Arduino_package/release/ folder detected!"
          # Define the payload
          payload='{"event": "Workflow run"}'
          # Generate the signature
          secret=${{ secrets.RTD_WEBHOOK_SECRET }}
          if [ -z "$secret" ]; then
            echo "Error: RTD_WEBHOOK_SECRET is not set."
            exit 1
          fi
          signature=$(echo -n "$payload" | openssl dgst -sha256 -hmac "$secret" | sed 's/^.* //')
          # Log the signature for debugging (remove this in production)
          echo "Generated Signature: $signature"
          # Example: Call a webhook URL with the signature
          response=$(curl -X POST -H "Content-Type: application/json" -H "X-Hub-Signature-256: sha256=$signature" -d "$payload" https://readthedocs.com/api/v2/webhook/ameba-doc-test-zzw/12628/ -w "%{http_code}" -o /dev/null)
          # Check the response code
          if [ "$response" -ne 200 ]; then
            echo "Error: Webhook request failed with status code $response"
            exit 1
          else
            echo "Webhook request successful"
          fi
