name: Find all h file names

on:
  workflow_dispatch:

jobs:
  Find-h-names:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Example guide links
        run: |
          echo "test1"
  
